apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee
  namespace: argo
spec:
  project: platform
  source:
    repoURL: https://github.com/anjeongkyun/learning-gitops.git
    path: gitops/products/coffee
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions: []
