apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
- name: mini
  releaseName: cart-api
  valuesFile: values.yaml
  version: 1.0.0