apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: order-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        host: "{{ .writerEndpoint }}"
        port: "{{ .port }}"
        schema: order
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
  - extract:
      key: order/db